from typing import List

class PlanningSceneInterface:
    def __init__(self, ns: str = ..., wait: bool = ...) -> None: ...
    def apply_collision_object(self, collision_object: object) -> bool: ...
    def get_known_object_names(self, with_type: bool = ...) -> List[str]: ...
    def get_known_object_names_in_roi(self, min_x: float, min_y: float, min_z: float, max_x: float, max_y: float, max_z: float, with_type: bool = ...) -> List[str]: ...
    def remove_collision_objects(self, object_ids: List[str]) -> None: ...
